<div class="col-md-12 mx-auto" style="max-width: 800px;">
    <div>
        <h2>Exercício 2</h2>
    </div>
    <div class="my-2">

        <h5>1. Crie um array</h5>
        <code>
            <?= $this->view->q1 ?>
        </code>
    </div>
    <div class="my-2">
        <h5>2. Popule este array com 7 números</h5>
        <code>
            <?= $this->view->q2 ?>
        </code>
    </div>
    <div class="my-2">
        <h5>3. Imprima o número da posição 3 do array</h5>
        <code>
            <?= $this->view->q3 ?>
        </code>
    </div>
    <div class="my-2">
        <h5>4. Crie uma variável com todas as posições do array no formato de string separado por vírgula</h5>

        <code>
            <?= $this->view->q4 ?>
        </code>
    </div>
    <div class="my-2">
        <h5>5. Crie um novo array a partir da variável no formato de string que foi criada e destrua o array anterior</h5>
        <code>
            <?= $this->view->q5 ?>
        </code>
    </div>
    <div class="my-2">
        <h5>6. Crie uma condição para verificar se existe o valor 14 no array</h5>
        <code>
            <?= $this->view->q6 ?>
        </code>
    </div>
    <div class="my-2">
        <h5>7. Faça uma busca em cada posição. Se o número da posição atual for menor que o da posição anterior (valor anterior que não foi excluído do array ainda), exclua esta posição</h5>
        <code>
            <?= $this->view->q7 ?>
        </code>
    </div>
    <div class="my-2">
        <h5>8. Remova a última posição deste array</h5>
        <code>
            <?= $this->view->q8 ?>
        </code>
    </div>
    <div class="my-2">
        <h5>9. Conte quantos elementos tem neste array</h5>
        <code>
            <?= $this->view->q9 ?>
        </code>
    </div>
    <div class="my-2">
        <h5>10. Inverta as posições deste array</h5>
        <code>
            <?= $this->view->q10 ?>
        </code>
    </div>
</div>