<div class="card mx-2" style="width: 18rem; height: 15rem;">
    <h5 class="card-header">Exercício 1</h5>
    <div class="card-body">
        <p class="card-text">Formulário onde é possível adicionar usuários.</p>
    </div>
    <div class="card-footer text-center">
        <a href="/ex1" class="btn btn-primary">Visualizar</a>
    </div>
</div>

<div class="card mx-2" style="width: 18rem; height: 15rem;">
    <h5 class="card-header">Exercício 2</h5>
    <div class="card-body">
        <p class="card-text">Série de manipulações utilizando array.</p>
    </div>
    <div class="card-footer text-center">
        <a href="/ex2" class="btn btn-primary">Visualizar</a>
    </div>
</div>

<div class="card mx-2" style="width: 18rem; height: 15rem;">
    <h5 class="card-header">Exercício 3</h5>
    <div class="card-body">
        <p class="card-text">Exemplo de consultas nas tabelas USUARIO e INFO.</p>
    </div>
    <div class="card-footer text-center">
        <a href="/ex3" class="btn btn-primary">Visualizar</a>
    </div>
</div>