<?php

namespace App\View\DefaultLayout; ?>

<!doctype html>
<html lang="pt_br">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js" integrity="sha384-ZfoEytSMLhLb1Qbwt7UEBdsjsJDd/M14/Uvu7cgxvZc8RQf6nkDemUVF9LDjRP9R" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/4228d1c16c.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="style.css">
    <link rel='shortcut icon' type='image/x-icon' href='favicon.ico' />

    <title>Teste Superlógica</title>

</head>

<body>
    <div class="d-flex flex-column min-vh-100">
        <header>
            <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
                <a class="navbar-brand">
                    <i class="fas fa-book-open fa-sm" alt=""></i>
                    Superlógica
                </a>
            </nav>
        </header>
        <main class="flex-fill">
            <div class="h-100 d-flex align-items-center justify-content-center" id="content">
                <?= $this->loadContent() ?>
            </div>
        </main>

        <footer class="footer stick-bottom mt-4 py-1 bg-dark">
            <div class="container">
                <div class="row">
                    <span class="text-muted">Desenvolvido por: Helyederson Naves</span>
                </div>
            </div>
        </footer>
    </div>
</body>

<?php if (isset($this->view->message)) { ?>
    <?php if ($this->view->message != '') { ?>
        <input id="message" name="message" type="hidden" value="<?= $this->view->message ?>">
        <script>
            console.log($('#message').val());
        </script>
    <?php } ?>
<?php } ?>

</html>